language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run eslint
  - npm test
  - npm run build
  - npm run build:docs
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/.vuepress/dist
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master
      repo: wont-org/utils
  - provider: npm
    email: lklk06@163.com
    api_key:
      secure: O9Vcuu18AJtEIOwvWmmh05PCo+DXHLfwk1o8NJWhJpH3wjBFIL5XkxB16yYSj+HxWmL1RIpQvT4HxB8WKm+uqnqkHOhairvKPDm2FUa3uu/fxhDhUE0Nc3d0pNXGi11QOzxFPa1aRn2uE4G1G2bHFtHc/6i9mMcw2XkXd8E6ZR6/B5n9EPHm5n6YkadKVKxCeDC/aOnh3QilmNP81f5Q/MUBuamL6gWEkTDgc/OrRHC3nU0NfR+rwVxh9wOtFE5GSE9Rh2RVsIL7ODiRnqAtEt1VAG61XRP2PfZ3nR5FD10YuPdxkpMkK4ZYUR6eFBAyLPZVVpG/o3GvqQilSLBen3cAVCB1lGxpyo2T4cNPCd3RgzwD68GopCFZmp9FCiPWjxJIYmQLBhMTt2Mw0ylIsaS3LbH1HGoVEi4Tr5UbnaXnO3OMc/BbiKOqmt1sIAjLdlN25ja9Pws11k+erj1EXUipUeLeq4qRlOQZfyHvuR3Ll1H5yar5ukEu1OPSo7q2ScvvPq8j7mpn7QyupgF9ofA41J158cZvwDyrz1CP2jpU9mYECamC++IgJcwOcFrqM6WtHDdiq9tyNlJqSW0R0DTdDYVHGRWigTTO/wDLNk87dImP8P396+g95K0GbH848L8AY2D0jlf/08rdn+KPrCAIwpnsUoLVhXRz/aixVQo=
    on:
      tags: true
      branch: master
      repo: wont-org/utils
    skip_cleanup: true
