language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run eslint
  - npm test
  - npm run build
  - npm run build:docs
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/.vuepress/dist
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master
      repo: wont-org/utils
  - provider: npm
    email: lklk06@163.com
    api_key:
      secure: onzdO6ilikZv1QTB8HX7wIvwlcqNW8fSXLEBsUcf1VdjRO0ZVtiPyvnsqsdykOOJnrluF2wNZ2dMYiRDBWbzUk9nyqH2IeQG0eMQGIznExgqKQnKC5W54IBbRjkS3g31Rv13Frl6SuR4RY2C021XqV5bU6V2konWD/qiYzzDDbcTR3EYZ7TPHvGGWC+RSWPODHNyCBFWV0eUNQPSJ/6pSAc0Yg8VqwmBxF62sT82QOi+InA7Saw4pznukM4EWFrZXr0zZsHKGNisEQ5tS8o5n0jpixm+X6+4SBOlocQLpk/9s+L+bltD9A1EzFpfG3hFRGvmMXerP6w1Z1sTxihzRIwPbirhnnHD4HH+TqYnh1ZOACd5KbRUyA6T8+5KRqXc5Ct8AEeoV7blPEtXUbjKlL+1NOYgY8ri411d4oB6kuJYvpSXYLelhdPwKAlTYspc4iRl9iZpMDUuyQfx5wN1bbfS1KpAnM9gc63mggv+PWYvITsTES8mXyhUuDK69QEHnzFVd5oU+WqfM1sIY6NTBAGdg5YjA1RAEmuXezBjUOUIj+zu0/J2v9y0kQ4zwordLLOURHUBifcphN8i+4JdASmtS97tWd6JosoqSFN+crNp9HH3Rm4MpWebReQk/R/5VvxpJYjI2C6qxqk+J1PjUdKHHZYcBeWeV3tGCa9fqG8=
    on:
      tags: true
      branch: master
      repo: wont-org/utils
    skip_cleanup: true
