language: node_js
node_js:
    - lts/*
install:
    - npm install
deploy:
    provider: pages
    script:
        - npm run build:pages
    skip_cleanup: true
    local_dir: docs/.vuepress/dist
    github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
    keep_history: true
    on:
        branch: master
#   provider: npm
#   email: "YOUR_EMAIL_ADDRESS"
#   api_key: "$NPM_TOKEN"
#   on:
#     tags: true
#     branch: master
