language: node_js
node_js:
    - lts/*
install:
    - npm install
script:
    - npm run eslint
    - npm test
    - npm run build
    - npm run build:docs
deploy:
    provider: pages
    skip_cleanup: true
    local_dir: docs/.vuepress/dist
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
