name: Check Status
on: [push, pull_request]

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
    - name: install
      run: npm install

    - name: eslint
      run: npm run eslint

    - name: coverage
      run: npm run coverage
