name: Deploy gh-pages
on:
  # push:
  #   branches:
  #     - master
  #     - dev
    # tags:
    #   - 'v*'
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1

      - name: install
        # run: npm install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci

      - name: eslint
        run: npm run eslint

      - name: coverage
        run: npm run coverage

      - name: build:docs
        run: npm run build:docs

      - name: moveCoverage
        run: sh ./scripts/mv-coverage.sh

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_KEY }}
          BRANCH: gh-pages
          FOLDER: ./docs/.vuepress/dist
