name: Deploy gh-pages
on:
  release:
    types: [published]
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.1

    - name: build
      run: npm run build:docs

    - name: moveCoverage
      run: sh ./scripts/mv-coverage.sh

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_KEY }}
        BRANCH: gh-pages
        FOLDER: ./docs/.vuepress/dist
