name: Deploy gh-pages
on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: set node version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: checkout
        uses: actions/checkout@v3

      - name: cache package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: create package-lock.json
        run: npm i --package-lock-only

      - name: hack for singe file
        run: |
          if [ ! -d "package-temp-dir" ]; then
            mkdir package-temp-dir
          fi
          cp package-lock.json package-temp-dir

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci

      # - name: eslint
      #   run: npm run eslint

      - name: coverage
        run: npm run coverage

      - name: build:docs
        run: npm run build:docs

      - name: moveCoverage
        run: sh ./scripts/mv-coverage.sh

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          token: ${{ secrets.GIT_KEY }}
          branch: gh-pages
          folder: ./docs/.vuepress/dist
