name: Npm Publish
on:
  push:
    tags:
      - 'v*'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - name: set node version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: set up NPM authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_KEY }}" > ~/.npmrc

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: pnpm install

      - name: test
        run: pnpm run test

      - name: build
        run: pnpm run build

      - name: publish
        run: pnpm publish --no-git-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_KEY }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
