name: Npm Publish
on:
  push:
    tags:
      - 'v*'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Set up NPM authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_KEY }}" > ~/.npmrc

      - name: install
        run: npm install

      - name: eslint
        run: npm run eslint

      - name: coverage
        run: npm run coverage

      - name: build
        run: npm run build

      - name: publish
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_KEY }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_KEY }}

